-- Word-of-mouth sharing. A "Share" button on any article snapshots that
-- node's content into this table so a link can be sent to someone who
-- has never used Hyfax, without requiring them to sign in to read it.
--
-- Only the share-article edge function (service role) inserts rows —
-- public access is select-only, and the client always looks up by exact
-- id (no listing UI), so this can't be used to browse other people's
-- shared content. `id` is a long random string generated by the edge
-- function, not a sequential/guessable key, which is what actually keeps
-- someone from enumerating other shares — RLS alone doesn't prevent that
-- since select is open to anyone by design.
create table if not exists shared_articles (
  id text primary key,
  topic_label text not null,
  node_type text not null,
  overview text,
  article text not null,
  created_at timestamptz not null default now()
);

alter table shared_articles enable row level security;

create policy "Anyone can read a shared article by id"
  on shared_articles for select
  using (true);

revoke insert, update, delete on shared_articles from anon, authenticated;
grant select on shared_articles to anon, authenticated;
