-- Finishes caching the Stale Bread campaign (migration 0039): the two
-- branches left "live" there (Starch Retrogradation, Day-Old Fried Rice)
-- now get the same instant-load treatment as the other 3 -- all 5 explore-
-- next chips off this root are precomputed now, none trigger a fresh
-- generation on first click. No code change needed -- node_cache's read
-- path already checks any direct child of a cached root, not just the
-- ones seeded so far. Articles generated live through rabbit-hole-proxy-v2
-- in Hyfax's real voice, reviewed before committing.
insert into node_cache (cache_key, root_cache_key, child_label, article)
values
  ('why does bread go stale::Starch Retrogradation', 'why does bread go stale', 'Starch Retrogradation', 'Here''s the part that should feel illegal — your bread was never actually a solid in the way you think, it was a crystal that got murdered by heat and is spending its entire shelf life trying to resurrect itself. Flour starch comes packed in tight little granules made of two molecules, amylose and amylopectin, coiled up in dense, ordered arrangements. Baking blasts that order apart — water floods in, heat uncoils the chains, and the granules swell and burst in a process called gelatinization, which is the only reason fresh bread has that soft, giving crumb at all. It''s a molecule mid-collapse, caught in a happy accident of texture.

But amylose and amylopectin don''t forget who they were. The second the loaf starts cooling, amylose, shorter and nimbler, snaps back into tight double-helix bundles within hours, while the slower, branchier amylopectin spends days crawling back toward its original crystalline order, dragging moisture out of the crumb and into itself as it goes. That realignment runs fastest around four degrees Celsius, which is exactly fridge temperature — the sweet spot where molecules have energy to move but no heat to stop them crystallizing, so fridge bread stales roughly six times faster than bread left on the counter. Freeze it instead and the molecules get locked in place, frozen mid-gelatinization, unable to recrystallize at all — which is the entire, beautifully specific reason freezer bread toasts back to life and fridge bread turns into a brick by Tuesday.'),
  ('why does bread go stale::Day-Old Fried Rice', 'why does bread go stale', 'Day-Old Fried Rice', 'There''s a reason restaurant kitchens treat leftover rice like it''s radioactive, and it has absolutely nothing to do with it going dry or stale — the real threat is a bacterium called Bacillus cereus, and it''s already inside the rice before you even cook it. This microbe forms spores so tough they shrug off boiling water, riding out the cooking process completely unbothered, then waking up the moment rice sits around at room temperature. Left out on the counter for a few hours, those spores germinate and start multiplying, and some strains churn out a toxin called cereulide as a byproduct.

Here''s the genuinely nasty twist — cereulide is heat-stable, meaning it laughs off your wok, your microwave, your reheat-until-steaming instincts, all of it. You can kill every living bacterium in that fried rice and the toxin they already made stays fully active, intact, and ready to cause vomiting and nausea within hours of eating it, a syndrome so associated with this exact scenario it''s literally nicknamed fried rice syndrome. The fix isn''t cooking it harder, it''s timing — getting rice into the fridge within about an hour or two of cooking, before the spores ever get the chance to wake up and start producing the one thing your stove can''t undo.');
